package com.thfdcsoft.framework.business.dao;

import com.thfdcsoft.framework.business.entity.BankUserInfo;
import com.thfdcsoft.framework.business.entity.BankUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BankUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    long countByExample(BankUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    int deleteByExample(BankUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    int deleteByPrimaryKey(String bankUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    int insert(BankUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    int insertSelective(BankUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    List<BankUserInfo> selectByExample(BankUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    BankUserInfo selectByPrimaryKey(String bankUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") BankUserInfo record, @Param("example") BankUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    int updateByExample(@Param("record") BankUserInfo record, @Param("example") BankUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    int updateByPrimaryKeySelective(BankUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    int updateByPrimaryKey(BankUserInfo record);
}