package com.thfdcsoft.framework.business.dao;

import com.thfdcsoft.framework.business.entity.BankInfo;
import com.thfdcsoft.framework.business.entity.BankInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BankInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    long countByExample(BankInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    int deleteByExample(BankInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    int deleteByPrimaryKey(String bankInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    int insert(BankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    int insertSelective(BankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    List<BankInfo> selectByExample(BankInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    BankInfo selectByPrimaryKey(String bankInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") BankInfo record, @Param("example") BankInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    int updateByExample(@Param("record") BankInfo record, @Param("example") BankInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    int updateByPrimaryKeySelective(BankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    int updateByPrimaryKey(BankInfo record);
}