package com.thfdcsoft.framework.business.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.thfdcsoft.framework.business.entity.TerminalInfo;
import com.thfdcsoft.framework.business.entity.TerminalInfoExample;

public interface TerminalInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	long countByExample(TerminalInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int deleteByExample(TerminalInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int deleteByPrimaryKey(String terminalId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int insert(TerminalInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int insertSelective(TerminalInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	List<TerminalInfo> selectByExample(TerminalInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	TerminalInfo selectByPrimaryKey(String terminalId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TerminalInfo record, @Param("example") TerminalInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int updateByExample(@Param("record") TerminalInfo record, @Param("example") TerminalInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int updateByPrimaryKeySelective(TerminalInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int updateByPrimaryKey(TerminalInfo record);

	TerminalInfo selectByDeployNumber(String deployNumber);
}