package com.thfdcsoft.framework.business.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.thfdcsoft.framework.business.entity.UsageRecord;
import com.thfdcsoft.framework.business.entity.UsageRecordExample;

public interface UsageRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USAGE_RECORD
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	long countByExample(UsageRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USAGE_RECORD
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int deleteByExample(UsageRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USAGE_RECORD
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int deleteByPrimaryKey(String recordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USAGE_RECORD
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int insert(UsageRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USAGE_RECORD
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int insertSelective(UsageRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USAGE_RECORD
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	List<UsageRecord> selectByExample(UsageRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USAGE_RECORD
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	UsageRecord selectByPrimaryKey(String recordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USAGE_RECORD
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int updateByExampleSelective(@Param("record") UsageRecord record, @Param("example") UsageRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USAGE_RECORD
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int updateByExample(@Param("record") UsageRecord record, @Param("example") UsageRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USAGE_RECORD
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int updateByPrimaryKeySelective(UsageRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USAGE_RECORD
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int updateByPrimaryKey(UsageRecord record);
}