package com.thfdcsoft.framework.business.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.thfdcsoft.framework.business.entity.UserInfo;
import com.thfdcsoft.framework.business.entity.UserInfoExample;

public interface UserInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	long countByExample(UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int deleteByExample(UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int insert(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int insertSelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	List<UserInfo> selectByExample(UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	UserInfo selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int updateByExampleSelective(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int updateByExample(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int updateByPrimaryKeySelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_INFO
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	int updateByPrimaryKey(UserInfo record);
	
}