package com.thfdcsoft.framework.business.entity;

public class BankInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_info.bank_info_id
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    private String bankInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_info.bank_name
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_info.bank_id
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    private String bankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_info.bank_number
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    private String bankNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_info.bank_info_id
     *
     * @return the value of bank_info.bank_info_id
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public String getBankInfoId() {
        return bankInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_info.bank_info_id
     *
     * @param bankInfoId the value for bank_info.bank_info_id
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public void setBankInfoId(String bankInfoId) {
        this.bankInfoId = bankInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_info.bank_name
     *
     * @return the value of bank_info.bank_name
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_info.bank_name
     *
     * @param bankName the value for bank_info.bank_name
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_info.bank_id
     *
     * @return the value of bank_info.bank_id
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_info.bank_id
     *
     * @param bankId the value for bank_info.bank_id
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_info.bank_number
     *
     * @return the value of bank_info.bank_number
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public String getBankNumber() {
        return bankNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_info.bank_number
     *
     * @param bankNumber the value for bank_info.bank_number
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public void setBankNumber(String bankNumber) {
        this.bankNumber = bankNumber;
    }
}