package com.thfdcsoft.framework.business.entity;

import java.util.ArrayList;
import java.util.List;

public class BankUserInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public BankUserInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBankUserIdIsNull() {
            addCriterion("bank_user_id is null");
            return (Criteria) this;
        }

        public Criteria andBankUserIdIsNotNull() {
            addCriterion("bank_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andBankUserIdEqualTo(String value) {
            addCriterion("bank_user_id =", value, "bankUserId");
            return (Criteria) this;
        }

        public Criteria andBankUserIdNotEqualTo(String value) {
            addCriterion("bank_user_id <>", value, "bankUserId");
            return (Criteria) this;
        }

        public Criteria andBankUserIdGreaterThan(String value) {
            addCriterion("bank_user_id >", value, "bankUserId");
            return (Criteria) this;
        }

        public Criteria andBankUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("bank_user_id >=", value, "bankUserId");
            return (Criteria) this;
        }

        public Criteria andBankUserIdLessThan(String value) {
            addCriterion("bank_user_id <", value, "bankUserId");
            return (Criteria) this;
        }

        public Criteria andBankUserIdLessThanOrEqualTo(String value) {
            addCriterion("bank_user_id <=", value, "bankUserId");
            return (Criteria) this;
        }

        public Criteria andBankUserIdLike(String value) {
            addCriterion("bank_user_id like", value, "bankUserId");
            return (Criteria) this;
        }

        public Criteria andBankUserIdNotLike(String value) {
            addCriterion("bank_user_id not like", value, "bankUserId");
            return (Criteria) this;
        }

        public Criteria andBankUserIdIn(List<String> values) {
            addCriterion("bank_user_id in", values, "bankUserId");
            return (Criteria) this;
        }

        public Criteria andBankUserIdNotIn(List<String> values) {
            addCriterion("bank_user_id not in", values, "bankUserId");
            return (Criteria) this;
        }

        public Criteria andBankUserIdBetween(String value1, String value2) {
            addCriterion("bank_user_id between", value1, value2, "bankUserId");
            return (Criteria) this;
        }

        public Criteria andBankUserIdNotBetween(String value1, String value2) {
            addCriterion("bank_user_id not between", value1, value2, "bankUserId");
            return (Criteria) this;
        }

        public Criteria andBankIdIsNull() {
            addCriterion("bank_id is null");
            return (Criteria) this;
        }

        public Criteria andBankIdIsNotNull() {
            addCriterion("bank_id is not null");
            return (Criteria) this;
        }

        public Criteria andBankIdEqualTo(String value) {
            addCriterion("bank_id =", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotEqualTo(String value) {
            addCriterion("bank_id <>", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThan(String value) {
            addCriterion("bank_id >", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThanOrEqualTo(String value) {
            addCriterion("bank_id >=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThan(String value) {
            addCriterion("bank_id <", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThanOrEqualTo(String value) {
            addCriterion("bank_id <=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLike(String value) {
            addCriterion("bank_id like", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotLike(String value) {
            addCriterion("bank_id not like", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdIn(List<String> values) {
            addCriterion("bank_id in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotIn(List<String> values) {
            addCriterion("bank_id not in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdBetween(String value1, String value2) {
            addCriterion("bank_id between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotBetween(String value1, String value2) {
            addCriterion("bank_id not between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankUserNameIsNull() {
            addCriterion("bank_user_name is null");
            return (Criteria) this;
        }

        public Criteria andBankUserNameIsNotNull() {
            addCriterion("bank_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andBankUserNameEqualTo(String value) {
            addCriterion("bank_user_name =", value, "bankUserName");
            return (Criteria) this;
        }

        public Criteria andBankUserNameNotEqualTo(String value) {
            addCriterion("bank_user_name <>", value, "bankUserName");
            return (Criteria) this;
        }

        public Criteria andBankUserNameGreaterThan(String value) {
            addCriterion("bank_user_name >", value, "bankUserName");
            return (Criteria) this;
        }

        public Criteria andBankUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("bank_user_name >=", value, "bankUserName");
            return (Criteria) this;
        }

        public Criteria andBankUserNameLessThan(String value) {
            addCriterion("bank_user_name <", value, "bankUserName");
            return (Criteria) this;
        }

        public Criteria andBankUserNameLessThanOrEqualTo(String value) {
            addCriterion("bank_user_name <=", value, "bankUserName");
            return (Criteria) this;
        }

        public Criteria andBankUserNameLike(String value) {
            addCriterion("bank_user_name like", value, "bankUserName");
            return (Criteria) this;
        }

        public Criteria andBankUserNameNotLike(String value) {
            addCriterion("bank_user_name not like", value, "bankUserName");
            return (Criteria) this;
        }

        public Criteria andBankUserNameIn(List<String> values) {
            addCriterion("bank_user_name in", values, "bankUserName");
            return (Criteria) this;
        }

        public Criteria andBankUserNameNotIn(List<String> values) {
            addCriterion("bank_user_name not in", values, "bankUserName");
            return (Criteria) this;
        }

        public Criteria andBankUserNameBetween(String value1, String value2) {
            addCriterion("bank_user_name between", value1, value2, "bankUserName");
            return (Criteria) this;
        }

        public Criteria andBankUserNameNotBetween(String value1, String value2) {
            addCriterion("bank_user_name not between", value1, value2, "bankUserName");
            return (Criteria) this;
        }

        public Criteria andBankUserIdcardIsNull() {
            addCriterion("bank_user_idCard is null");
            return (Criteria) this;
        }

        public Criteria andBankUserIdcardIsNotNull() {
            addCriterion("bank_user_idCard is not null");
            return (Criteria) this;
        }

        public Criteria andBankUserIdcardEqualTo(String value) {
            addCriterion("bank_user_idCard =", value, "bankUserIdcard");
            return (Criteria) this;
        }

        public Criteria andBankUserIdcardNotEqualTo(String value) {
            addCriterion("bank_user_idCard <>", value, "bankUserIdcard");
            return (Criteria) this;
        }

        public Criteria andBankUserIdcardGreaterThan(String value) {
            addCriterion("bank_user_idCard >", value, "bankUserIdcard");
            return (Criteria) this;
        }

        public Criteria andBankUserIdcardGreaterThanOrEqualTo(String value) {
            addCriterion("bank_user_idCard >=", value, "bankUserIdcard");
            return (Criteria) this;
        }

        public Criteria andBankUserIdcardLessThan(String value) {
            addCriterion("bank_user_idCard <", value, "bankUserIdcard");
            return (Criteria) this;
        }

        public Criteria andBankUserIdcardLessThanOrEqualTo(String value) {
            addCriterion("bank_user_idCard <=", value, "bankUserIdcard");
            return (Criteria) this;
        }

        public Criteria andBankUserIdcardLike(String value) {
            addCriterion("bank_user_idCard like", value, "bankUserIdcard");
            return (Criteria) this;
        }

        public Criteria andBankUserIdcardNotLike(String value) {
            addCriterion("bank_user_idCard not like", value, "bankUserIdcard");
            return (Criteria) this;
        }

        public Criteria andBankUserIdcardIn(List<String> values) {
            addCriterion("bank_user_idCard in", values, "bankUserIdcard");
            return (Criteria) this;
        }

        public Criteria andBankUserIdcardNotIn(List<String> values) {
            addCriterion("bank_user_idCard not in", values, "bankUserIdcard");
            return (Criteria) this;
        }

        public Criteria andBankUserIdcardBetween(String value1, String value2) {
            addCriterion("bank_user_idCard between", value1, value2, "bankUserIdcard");
            return (Criteria) this;
        }

        public Criteria andBankUserIdcardNotBetween(String value1, String value2) {
            addCriterion("bank_user_idCard not between", value1, value2, "bankUserIdcard");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bank_user_info
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 08 15:04:30 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bank_user_info
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}