package com.thfdcsoft.framework.business.entity;

public class BankUserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_user_info.bank_user_id
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    private String bankUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_user_info.bank_id
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    private String bankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_user_info.bank_user_name
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    private String bankUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_user_info.bank_user_idCard
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    private String bankUserIdcard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_user_info.bank_user_id
     *
     * @return the value of bank_user_info.bank_user_id
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public String getBankUserId() {
        return bankUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_user_info.bank_user_id
     *
     * @param bankUserId the value for bank_user_info.bank_user_id
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public void setBankUserId(String bankUserId) {
        this.bankUserId = bankUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_user_info.bank_id
     *
     * @return the value of bank_user_info.bank_id
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_user_info.bank_id
     *
     * @param bankId the value for bank_user_info.bank_id
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_user_info.bank_user_name
     *
     * @return the value of bank_user_info.bank_user_name
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public String getBankUserName() {
        return bankUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_user_info.bank_user_name
     *
     * @param bankUserName the value for bank_user_info.bank_user_name
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public void setBankUserName(String bankUserName) {
        this.bankUserName = bankUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_user_info.bank_user_idCard
     *
     * @return the value of bank_user_info.bank_user_idCard
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public String getBankUserIdcard() {
        return bankUserIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_user_info.bank_user_idCard
     *
     * @param bankUserIdcard the value for bank_user_info.bank_user_idCard
     *
     * @mbg.generated Mon Oct 08 15:04:30 CST 2018
     */
    public void setBankUserIdcard(String bankUserIdcard) {
        this.bankUserIdcard = bankUserIdcard;
    }
}