package com.thfdcsoft.framework.business.entity;

public class TerminalInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TERMINAL_INFO.TERMINAL_ID
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String terminalId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TERMINAL_INFO.TERMINAL_MODEL
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String terminalModel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TERMINAL_INFO.TERM_GROUP_ID
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String termGroupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TERMINAL_INFO.ADMI_AREA_ID
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String admiAreaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TERMINAL_INFO.TERM_DEPLOY_ADDR
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String termDeployAddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TERMINAL_INFO.TERMINAL_STATUS
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String terminalStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TERMINAL_INFO.REMAINING_PAPER
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String remainingPaper;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TERMINAL_INFO.DEPLOY_NUMBER
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String deployNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TERMINAL_INFO.EXTEND_FIELD
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String extendField;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TERMINAL_INFO.TERMINAL_ID
	 * @return  the value of TERMINAL_INFO.TERMINAL_ID
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getTerminalId() {
		return terminalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TERMINAL_INFO.TERMINAL_ID
	 * @param terminalId  the value for TERMINAL_INFO.TERMINAL_ID
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setTerminalId(String terminalId) {
		this.terminalId = terminalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TERMINAL_INFO.TERMINAL_MODEL
	 * @return  the value of TERMINAL_INFO.TERMINAL_MODEL
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getTerminalModel() {
		return terminalModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TERMINAL_INFO.TERMINAL_MODEL
	 * @param terminalModel  the value for TERMINAL_INFO.TERMINAL_MODEL
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setTerminalModel(String terminalModel) {
		this.terminalModel = terminalModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TERMINAL_INFO.TERM_GROUP_ID
	 * @return  the value of TERMINAL_INFO.TERM_GROUP_ID
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getTermGroupId() {
		return termGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TERMINAL_INFO.TERM_GROUP_ID
	 * @param termGroupId  the value for TERMINAL_INFO.TERM_GROUP_ID
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setTermGroupId(String termGroupId) {
		this.termGroupId = termGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TERMINAL_INFO.ADMI_AREA_ID
	 * @return  the value of TERMINAL_INFO.ADMI_AREA_ID
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getAdmiAreaId() {
		return admiAreaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TERMINAL_INFO.ADMI_AREA_ID
	 * @param admiAreaId  the value for TERMINAL_INFO.ADMI_AREA_ID
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setAdmiAreaId(String admiAreaId) {
		this.admiAreaId = admiAreaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TERMINAL_INFO.TERM_DEPLOY_ADDR
	 * @return  the value of TERMINAL_INFO.TERM_DEPLOY_ADDR
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getTermDeployAddr() {
		return termDeployAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TERMINAL_INFO.TERM_DEPLOY_ADDR
	 * @param termDeployAddr  the value for TERMINAL_INFO.TERM_DEPLOY_ADDR
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setTermDeployAddr(String termDeployAddr) {
		this.termDeployAddr = termDeployAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TERMINAL_INFO.TERMINAL_STATUS
	 * @return  the value of TERMINAL_INFO.TERMINAL_STATUS
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getTerminalStatus() {
		return terminalStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TERMINAL_INFO.TERMINAL_STATUS
	 * @param terminalStatus  the value for TERMINAL_INFO.TERMINAL_STATUS
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setTerminalStatus(String terminalStatus) {
		this.terminalStatus = terminalStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TERMINAL_INFO.REMAINING_PAPER
	 * @return  the value of TERMINAL_INFO.REMAINING_PAPER
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getRemainingPaper() {
		return remainingPaper;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TERMINAL_INFO.REMAINING_PAPER
	 * @param remainingPaper  the value for TERMINAL_INFO.REMAINING_PAPER
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setRemainingPaper(String remainingPaper) {
		this.remainingPaper = remainingPaper;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TERMINAL_INFO.DEPLOY_NUMBER
	 * @return  the value of TERMINAL_INFO.DEPLOY_NUMBER
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getDeployNumber() {
		return deployNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TERMINAL_INFO.DEPLOY_NUMBER
	 * @param deployNumber  the value for TERMINAL_INFO.DEPLOY_NUMBER
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setDeployNumber(String deployNumber) {
		this.deployNumber = deployNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TERMINAL_INFO.EXTEND_FIELD
	 * @return  the value of TERMINAL_INFO.EXTEND_FIELD
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getExtendField() {
		return extendField;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TERMINAL_INFO.EXTEND_FIELD
	 * @param extendField  the value for TERMINAL_INFO.EXTEND_FIELD
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setExtendField(String extendField) {
		this.extendField = extendField;
	}
}