package com.thfdcsoft.framework.business.entity;

public class UserInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_INFO.USER_ID
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_INFO.ROLE_ID
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_INFO.USER_NAME
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_INFO.USER_MOBILE
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String userMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_INFO.USER_EMAIL
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String userEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_INFO.LOGIN_USERNAME
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String loginUsername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_INFO.LOGIN_PASSWORD
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String loginPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_INFO.USER_STATUS
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String userStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_INFO.USER_IDNUMBER
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	private String userIdnumber;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_INFO.USER_ID
	 * @return  the value of USER_INFO.USER_ID
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_INFO.USER_ID
	 * @param userId  the value for USER_INFO.USER_ID
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_INFO.ROLE_ID
	 * @return  the value of USER_INFO.ROLE_ID
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_INFO.ROLE_ID
	 * @param roleId  the value for USER_INFO.ROLE_ID
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_INFO.USER_NAME
	 * @return  the value of USER_INFO.USER_NAME
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_INFO.USER_NAME
	 * @param userName  the value for USER_INFO.USER_NAME
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_INFO.USER_MOBILE
	 * @return  the value of USER_INFO.USER_MOBILE
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getUserMobile() {
		return userMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_INFO.USER_MOBILE
	 * @param userMobile  the value for USER_INFO.USER_MOBILE
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setUserMobile(String userMobile) {
		this.userMobile = userMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_INFO.USER_EMAIL
	 * @return  the value of USER_INFO.USER_EMAIL
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_INFO.USER_EMAIL
	 * @param userEmail  the value for USER_INFO.USER_EMAIL
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_INFO.LOGIN_USERNAME
	 * @return  the value of USER_INFO.LOGIN_USERNAME
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getLoginUsername() {
		return loginUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_INFO.LOGIN_USERNAME
	 * @param loginUsername  the value for USER_INFO.LOGIN_USERNAME
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setLoginUsername(String loginUsername) {
		this.loginUsername = loginUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_INFO.LOGIN_PASSWORD
	 * @return  the value of USER_INFO.LOGIN_PASSWORD
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getLoginPassword() {
		return loginPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_INFO.LOGIN_PASSWORD
	 * @param loginPassword  the value for USER_INFO.LOGIN_PASSWORD
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_INFO.USER_STATUS
	 * @return  the value of USER_INFO.USER_STATUS
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getUserStatus() {
		return userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_INFO.USER_STATUS
	 * @param userStatus  the value for USER_INFO.USER_STATUS
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_INFO.USER_IDNUMBER
	 * @return  the value of USER_INFO.USER_IDNUMBER
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public String getUserIdnumber() {
		return userIdnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_INFO.USER_IDNUMBER
	 * @param userIdnumber  the value for USER_INFO.USER_IDNUMBER
	 * @mbg.generated  Thu Jun 28 09:55:44 CST 2018
	 */
	public void setUserIdnumber(String userIdnumber) {
		this.userIdnumber = userIdnumber;
	}
}