package com.thfdcsoft.framework.manage.entity;

public class AuthorizeInfoKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column AUTHORIZE_INFO.ROLE_ID
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	private String roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column AUTHORIZE_INFO.MODULE_ID
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	private String moduleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column AUTHORIZE_INFO.ROLE_ID
	 * @return  the value of AUTHORIZE_INFO.ROLE_ID
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column AUTHORIZE_INFO.ROLE_ID
	 * @param roleId  the value for AUTHORIZE_INFO.ROLE_ID
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column AUTHORIZE_INFO.MODULE_ID
	 * @return  the value of AUTHORIZE_INFO.MODULE_ID
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public String getModuleId() {
		return moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column AUTHORIZE_INFO.MODULE_ID
	 * @param moduleId  the value for AUTHORIZE_INFO.MODULE_ID
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public void setModuleId(String moduleId) {
		this.moduleId = moduleId;
	}
}