package com.thfdcsoft.framework.manage.entity;

public class BusiInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUSI_INFO.BUSI_NUMBER
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    private String busiNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUSI_INFO.TOBE_PRINTED
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    private String tobePrinted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUSI_INFO.BUSI_NUMBER
     *
     * @return the value of BUSI_INFO.BUSI_NUMBER
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    public String getBusiNumber() {
        return busiNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUSI_INFO.BUSI_NUMBER
     *
     * @param busiNumber the value for BUSI_INFO.BUSI_NUMBER
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    public void setBusiNumber(String busiNumber) {
        this.busiNumber = busiNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUSI_INFO.TOBE_PRINTED
     *
     * @return the value of BUSI_INFO.TOBE_PRINTED
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    public String getTobePrinted() {
        return tobePrinted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUSI_INFO.TOBE_PRINTED
     *
     * @param tobePrinted the value for BUSI_INFO.TOBE_PRINTED
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    public void setTobePrinted(String tobePrinted) {
        this.tobePrinted = tobePrinted;
    }

}