package com.thfdcsoft.framework.manage.entity;

import java.util.ArrayList;
import java.util.List;

public class BusiInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    public BusiInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBusiNumberIsNull() {
            addCriterion("BUSI_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andBusiNumberIsNotNull() {
            addCriterion("BUSI_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andBusiNumberEqualTo(String value) {
            addCriterion("BUSI_NUMBER =", value, "busiNumber");
            return (Criteria) this;
        }

        public Criteria andBusiNumberNotEqualTo(String value) {
            addCriterion("BUSI_NUMBER <>", value, "busiNumber");
            return (Criteria) this;
        }

        public Criteria andBusiNumberGreaterThan(String value) {
            addCriterion("BUSI_NUMBER >", value, "busiNumber");
            return (Criteria) this;
        }

        public Criteria andBusiNumberGreaterThanOrEqualTo(String value) {
            addCriterion("BUSI_NUMBER >=", value, "busiNumber");
            return (Criteria) this;
        }

        public Criteria andBusiNumberLessThan(String value) {
            addCriterion("BUSI_NUMBER <", value, "busiNumber");
            return (Criteria) this;
        }

        public Criteria andBusiNumberLessThanOrEqualTo(String value) {
            addCriterion("BUSI_NUMBER <=", value, "busiNumber");
            return (Criteria) this;
        }

        public Criteria andBusiNumberLike(String value) {
            addCriterion("BUSI_NUMBER like", value, "busiNumber");
            return (Criteria) this;
        }

        public Criteria andBusiNumberNotLike(String value) {
            addCriterion("BUSI_NUMBER not like", value, "busiNumber");
            return (Criteria) this;
        }

        public Criteria andBusiNumberIn(List<String> values) {
            addCriterion("BUSI_NUMBER in", values, "busiNumber");
            return (Criteria) this;
        }

        public Criteria andBusiNumberNotIn(List<String> values) {
            addCriterion("BUSI_NUMBER not in", values, "busiNumber");
            return (Criteria) this;
        }

        public Criteria andBusiNumberBetween(String value1, String value2) {
            addCriterion("BUSI_NUMBER between", value1, value2, "busiNumber");
            return (Criteria) this;
        }

        public Criteria andBusiNumberNotBetween(String value1, String value2) {
            addCriterion("BUSI_NUMBER not between", value1, value2, "busiNumber");
            return (Criteria) this;
        }

        public Criteria andTobePrintedIsNull() {
            addCriterion("TOBE_PRINTED is null");
            return (Criteria) this;
        }

        public Criteria andTobePrintedIsNotNull() {
            addCriterion("TOBE_PRINTED is not null");
            return (Criteria) this;
        }

        public Criteria andTobePrintedEqualTo(String value) {
            addCriterion("TOBE_PRINTED =", value, "tobePrinted");
            return (Criteria) this;
        }

        public Criteria andTobePrintedNotEqualTo(String value) {
            addCriterion("TOBE_PRINTED <>", value, "tobePrinted");
            return (Criteria) this;
        }

        public Criteria andTobePrintedGreaterThan(String value) {
            addCriterion("TOBE_PRINTED >", value, "tobePrinted");
            return (Criteria) this;
        }

        public Criteria andTobePrintedGreaterThanOrEqualTo(String value) {
            addCriterion("TOBE_PRINTED >=", value, "tobePrinted");
            return (Criteria) this;
        }

        public Criteria andTobePrintedLessThan(String value) {
            addCriterion("TOBE_PRINTED <", value, "tobePrinted");
            return (Criteria) this;
        }

        public Criteria andTobePrintedLessThanOrEqualTo(String value) {
            addCriterion("TOBE_PRINTED <=", value, "tobePrinted");
            return (Criteria) this;
        }

        public Criteria andTobePrintedLike(String value) {
            addCriterion("TOBE_PRINTED like", value, "tobePrinted");
            return (Criteria) this;
        }

        public Criteria andTobePrintedNotLike(String value) {
            addCriterion("TOBE_PRINTED not like", value, "tobePrinted");
            return (Criteria) this;
        }

        public Criteria andTobePrintedIn(List<String> values) {
            addCriterion("TOBE_PRINTED in", values, "tobePrinted");
            return (Criteria) this;
        }

        public Criteria andTobePrintedNotIn(List<String> values) {
            addCriterion("TOBE_PRINTED not in", values, "tobePrinted");
            return (Criteria) this;
        }

        public Criteria andTobePrintedBetween(String value1, String value2) {
            addCriterion("TOBE_PRINTED between", value1, value2, "tobePrinted");
            return (Criteria) this;
        }

        public Criteria andTobePrintedNotBetween(String value1, String value2) {
            addCriterion("TOBE_PRINTED not between", value1, value2, "tobePrinted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BUSI_INFO
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 12 13:49:07 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}