package com.thfdcsoft.framework.manage.entity;

import java.util.ArrayList;
import java.util.List;

public class HelpExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	public HelpExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRecordIdIsNull() {
			addCriterion("RECORD_ID is null");
			return (Criteria) this;
		}

		public Criteria andRecordIdIsNotNull() {
			addCriterion("RECORD_ID is not null");
			return (Criteria) this;
		}

		public Criteria andRecordIdEqualTo(String value) {
			addCriterion("RECORD_ID =", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotEqualTo(String value) {
			addCriterion("RECORD_ID <>", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdGreaterThan(String value) {
			addCriterion("RECORD_ID >", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdGreaterThanOrEqualTo(String value) {
			addCriterion("RECORD_ID >=", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdLessThan(String value) {
			addCriterion("RECORD_ID <", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdLessThanOrEqualTo(String value) {
			addCriterion("RECORD_ID <=", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdLike(String value) {
			addCriterion("RECORD_ID like", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotLike(String value) {
			addCriterion("RECORD_ID not like", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdIn(List<String> values) {
			addCriterion("RECORD_ID in", values, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotIn(List<String> values) {
			addCriterion("RECORD_ID not in", values, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdBetween(String value1, String value2) {
			addCriterion("RECORD_ID between", value1, value2, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotBetween(String value1, String value2) {
			addCriterion("RECORD_ID not between", value1, value2, "recordId");
			return (Criteria) this;
		}

		public Criteria andHelpIdIsNull() {
			addCriterion("HELP_ID is null");
			return (Criteria) this;
		}

		public Criteria andHelpIdIsNotNull() {
			addCriterion("HELP_ID is not null");
			return (Criteria) this;
		}

		public Criteria andHelpIdEqualTo(String value) {
			addCriterion("HELP_ID =", value, "helpId");
			return (Criteria) this;
		}

		public Criteria andHelpIdNotEqualTo(String value) {
			addCriterion("HELP_ID <>", value, "helpId");
			return (Criteria) this;
		}

		public Criteria andHelpIdGreaterThan(String value) {
			addCriterion("HELP_ID >", value, "helpId");
			return (Criteria) this;
		}

		public Criteria andHelpIdGreaterThanOrEqualTo(String value) {
			addCriterion("HELP_ID >=", value, "helpId");
			return (Criteria) this;
		}

		public Criteria andHelpIdLessThan(String value) {
			addCriterion("HELP_ID <", value, "helpId");
			return (Criteria) this;
		}

		public Criteria andHelpIdLessThanOrEqualTo(String value) {
			addCriterion("HELP_ID <=", value, "helpId");
			return (Criteria) this;
		}

		public Criteria andHelpIdLike(String value) {
			addCriterion("HELP_ID like", value, "helpId");
			return (Criteria) this;
		}

		public Criteria andHelpIdNotLike(String value) {
			addCriterion("HELP_ID not like", value, "helpId");
			return (Criteria) this;
		}

		public Criteria andHelpIdIn(List<String> values) {
			addCriterion("HELP_ID in", values, "helpId");
			return (Criteria) this;
		}

		public Criteria andHelpIdNotIn(List<String> values) {
			addCriterion("HELP_ID not in", values, "helpId");
			return (Criteria) this;
		}

		public Criteria andHelpIdBetween(String value1, String value2) {
			addCriterion("HELP_ID between", value1, value2, "helpId");
			return (Criteria) this;
		}

		public Criteria andHelpIdNotBetween(String value1, String value2) {
			addCriterion("HELP_ID not between", value1, value2, "helpId");
			return (Criteria) this;
		}

		public Criteria andHelpTitleIsNull() {
			addCriterion("HELP_TITLE is null");
			return (Criteria) this;
		}

		public Criteria andHelpTitleIsNotNull() {
			addCriterion("HELP_TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andHelpTitleEqualTo(String value) {
			addCriterion("HELP_TITLE =", value, "helpTitle");
			return (Criteria) this;
		}

		public Criteria andHelpTitleNotEqualTo(String value) {
			addCriterion("HELP_TITLE <>", value, "helpTitle");
			return (Criteria) this;
		}

		public Criteria andHelpTitleGreaterThan(String value) {
			addCriterion("HELP_TITLE >", value, "helpTitle");
			return (Criteria) this;
		}

		public Criteria andHelpTitleGreaterThanOrEqualTo(String value) {
			addCriterion("HELP_TITLE >=", value, "helpTitle");
			return (Criteria) this;
		}

		public Criteria andHelpTitleLessThan(String value) {
			addCriterion("HELP_TITLE <", value, "helpTitle");
			return (Criteria) this;
		}

		public Criteria andHelpTitleLessThanOrEqualTo(String value) {
			addCriterion("HELP_TITLE <=", value, "helpTitle");
			return (Criteria) this;
		}

		public Criteria andHelpTitleLike(String value) {
			addCriterion("HELP_TITLE like", value, "helpTitle");
			return (Criteria) this;
		}

		public Criteria andHelpTitleNotLike(String value) {
			addCriterion("HELP_TITLE not like", value, "helpTitle");
			return (Criteria) this;
		}

		public Criteria andHelpTitleIn(List<String> values) {
			addCriterion("HELP_TITLE in", values, "helpTitle");
			return (Criteria) this;
		}

		public Criteria andHelpTitleNotIn(List<String> values) {
			addCriterion("HELP_TITLE not in", values, "helpTitle");
			return (Criteria) this;
		}

		public Criteria andHelpTitleBetween(String value1, String value2) {
			addCriterion("HELP_TITLE between", value1, value2, "helpTitle");
			return (Criteria) this;
		}

		public Criteria andHelpTitleNotBetween(String value1, String value2) {
			addCriterion("HELP_TITLE not between", value1, value2, "helpTitle");
			return (Criteria) this;
		}

		public Criteria andHelpContentIsNull() {
			addCriterion("HELP_CONTENT is null");
			return (Criteria) this;
		}

		public Criteria andHelpContentIsNotNull() {
			addCriterion("HELP_CONTENT is not null");
			return (Criteria) this;
		}

		public Criteria andHelpContentEqualTo(String value) {
			addCriterion("HELP_CONTENT =", value, "helpContent");
			return (Criteria) this;
		}

		public Criteria andHelpContentNotEqualTo(String value) {
			addCriterion("HELP_CONTENT <>", value, "helpContent");
			return (Criteria) this;
		}

		public Criteria andHelpContentGreaterThan(String value) {
			addCriterion("HELP_CONTENT >", value, "helpContent");
			return (Criteria) this;
		}

		public Criteria andHelpContentGreaterThanOrEqualTo(String value) {
			addCriterion("HELP_CONTENT >=", value, "helpContent");
			return (Criteria) this;
		}

		public Criteria andHelpContentLessThan(String value) {
			addCriterion("HELP_CONTENT <", value, "helpContent");
			return (Criteria) this;
		}

		public Criteria andHelpContentLessThanOrEqualTo(String value) {
			addCriterion("HELP_CONTENT <=", value, "helpContent");
			return (Criteria) this;
		}

		public Criteria andHelpContentLike(String value) {
			addCriterion("HELP_CONTENT like", value, "helpContent");
			return (Criteria) this;
		}

		public Criteria andHelpContentNotLike(String value) {
			addCriterion("HELP_CONTENT not like", value, "helpContent");
			return (Criteria) this;
		}

		public Criteria andHelpContentIn(List<String> values) {
			addCriterion("HELP_CONTENT in", values, "helpContent");
			return (Criteria) this;
		}

		public Criteria andHelpContentNotIn(List<String> values) {
			addCriterion("HELP_CONTENT not in", values, "helpContent");
			return (Criteria) this;
		}

		public Criteria andHelpContentBetween(String value1, String value2) {
			addCriterion("HELP_CONTENT between", value1, value2, "helpContent");
			return (Criteria) this;
		}

		public Criteria andHelpContentNotBetween(String value1, String value2) {
			addCriterion("HELP_CONTENT not between", value1, value2, "helpContent");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table help
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 04 11:07:41 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}