package com.thfdcsoft.framework.manage.entity;

public class ModuleInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODULE_INFO.MODULE_ID
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	private String moduleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODULE_INFO.MODULE_NAME
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	private String moduleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODULE_INFO.MODULE_DESCRIBE
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	private String moduleDescribe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODULE_INFO.MODULE_URL
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	private String moduleUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODULE_INFO.MODULE_LEVEL
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	private String moduleLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODULE_INFO.SUPE_MODULE_ID
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	private String supeModuleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODULE_INFO.DISPLAY_ORDER
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	private String displayOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODULE_INFO.ICON_CSS
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	private String iconCss;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODULE_INFO.MODULE_ID
	 * @return  the value of MODULE_INFO.MODULE_ID
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public String getModuleId() {
		return moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODULE_INFO.MODULE_ID
	 * @param moduleId  the value for MODULE_INFO.MODULE_ID
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public void setModuleId(String moduleId) {
		this.moduleId = moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODULE_INFO.MODULE_NAME
	 * @return  the value of MODULE_INFO.MODULE_NAME
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public String getModuleName() {
		return moduleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODULE_INFO.MODULE_NAME
	 * @param moduleName  the value for MODULE_INFO.MODULE_NAME
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODULE_INFO.MODULE_DESCRIBE
	 * @return  the value of MODULE_INFO.MODULE_DESCRIBE
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public String getModuleDescribe() {
		return moduleDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODULE_INFO.MODULE_DESCRIBE
	 * @param moduleDescribe  the value for MODULE_INFO.MODULE_DESCRIBE
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public void setModuleDescribe(String moduleDescribe) {
		this.moduleDescribe = moduleDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODULE_INFO.MODULE_URL
	 * @return  the value of MODULE_INFO.MODULE_URL
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public String getModuleUrl() {
		return moduleUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODULE_INFO.MODULE_URL
	 * @param moduleUrl  the value for MODULE_INFO.MODULE_URL
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public void setModuleUrl(String moduleUrl) {
		this.moduleUrl = moduleUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODULE_INFO.MODULE_LEVEL
	 * @return  the value of MODULE_INFO.MODULE_LEVEL
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public String getModuleLevel() {
		return moduleLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODULE_INFO.MODULE_LEVEL
	 * @param moduleLevel  the value for MODULE_INFO.MODULE_LEVEL
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public void setModuleLevel(String moduleLevel) {
		this.moduleLevel = moduleLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODULE_INFO.SUPE_MODULE_ID
	 * @return  the value of MODULE_INFO.SUPE_MODULE_ID
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public String getSupeModuleId() {
		return supeModuleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODULE_INFO.SUPE_MODULE_ID
	 * @param supeModuleId  the value for MODULE_INFO.SUPE_MODULE_ID
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public void setSupeModuleId(String supeModuleId) {
		this.supeModuleId = supeModuleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODULE_INFO.DISPLAY_ORDER
	 * @return  the value of MODULE_INFO.DISPLAY_ORDER
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public String getDisplayOrder() {
		return displayOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODULE_INFO.DISPLAY_ORDER
	 * @param displayOrder  the value for MODULE_INFO.DISPLAY_ORDER
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public void setDisplayOrder(String displayOrder) {
		this.displayOrder = displayOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODULE_INFO.ICON_CSS
	 * @return  the value of MODULE_INFO.ICON_CSS
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public String getIconCss() {
		return iconCss;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODULE_INFO.ICON_CSS
	 * @param iconCss  the value for MODULE_INFO.ICON_CSS
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public void setIconCss(String iconCss) {
		this.iconCss = iconCss;
	}
}