package com.thfdcsoft.framework.manage.entity;

import java.util.ArrayList;
import java.util.List;

public class OrgAgentInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public OrgAgentInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAgentIdIsNull() {
			addCriterion("AGENT_ID is null");
			return (Criteria) this;
		}

		public Criteria andAgentIdIsNotNull() {
			addCriterion("AGENT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andAgentIdEqualTo(String value) {
			addCriterion("AGENT_ID =", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdNotEqualTo(String value) {
			addCriterion("AGENT_ID <>", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdGreaterThan(String value) {
			addCriterion("AGENT_ID >", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdGreaterThanOrEqualTo(String value) {
			addCriterion("AGENT_ID >=", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdLessThan(String value) {
			addCriterion("AGENT_ID <", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdLessThanOrEqualTo(String value) {
			addCriterion("AGENT_ID <=", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdLike(String value) {
			addCriterion("AGENT_ID like", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdNotLike(String value) {
			addCriterion("AGENT_ID not like", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdIn(List<String> values) {
			addCriterion("AGENT_ID in", values, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdNotIn(List<String> values) {
			addCriterion("AGENT_ID not in", values, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdBetween(String value1, String value2) {
			addCriterion("AGENT_ID between", value1, value2, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdNotBetween(String value1, String value2) {
			addCriterion("AGENT_ID not between", value1, value2, "agentId");
			return (Criteria) this;
		}

		public Criteria andOrgIdIsNull() {
			addCriterion("ORG_ID is null");
			return (Criteria) this;
		}

		public Criteria andOrgIdIsNotNull() {
			addCriterion("ORG_ID is not null");
			return (Criteria) this;
		}

		public Criteria andOrgIdEqualTo(String value) {
			addCriterion("ORG_ID =", value, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdNotEqualTo(String value) {
			addCriterion("ORG_ID <>", value, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdGreaterThan(String value) {
			addCriterion("ORG_ID >", value, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdGreaterThanOrEqualTo(String value) {
			addCriterion("ORG_ID >=", value, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdLessThan(String value) {
			addCriterion("ORG_ID <", value, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdLessThanOrEqualTo(String value) {
			addCriterion("ORG_ID <=", value, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdLike(String value) {
			addCriterion("ORG_ID like", value, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdNotLike(String value) {
			addCriterion("ORG_ID not like", value, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdIn(List<String> values) {
			addCriterion("ORG_ID in", values, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdNotIn(List<String> values) {
			addCriterion("ORG_ID not in", values, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdBetween(String value1, String value2) {
			addCriterion("ORG_ID between", value1, value2, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdNotBetween(String value1, String value2) {
			addCriterion("ORG_ID not between", value1, value2, "orgId");
			return (Criteria) this;
		}

		public Criteria andAgentIdNumberIsNull() {
			addCriterion("AGENT_ID_NUMBER is null");
			return (Criteria) this;
		}

		public Criteria andAgentIdNumberIsNotNull() {
			addCriterion("AGENT_ID_NUMBER is not null");
			return (Criteria) this;
		}

		public Criteria andAgentIdNumberEqualTo(String value) {
			addCriterion("AGENT_ID_NUMBER =", value, "agentIdNumber");
			return (Criteria) this;
		}

		public Criteria andAgentIdNumberNotEqualTo(String value) {
			addCriterion("AGENT_ID_NUMBER <>", value, "agentIdNumber");
			return (Criteria) this;
		}

		public Criteria andAgentIdNumberGreaterThan(String value) {
			addCriterion("AGENT_ID_NUMBER >", value, "agentIdNumber");
			return (Criteria) this;
		}

		public Criteria andAgentIdNumberGreaterThanOrEqualTo(String value) {
			addCriterion("AGENT_ID_NUMBER >=", value, "agentIdNumber");
			return (Criteria) this;
		}

		public Criteria andAgentIdNumberLessThan(String value) {
			addCriterion("AGENT_ID_NUMBER <", value, "agentIdNumber");
			return (Criteria) this;
		}

		public Criteria andAgentIdNumberLessThanOrEqualTo(String value) {
			addCriterion("AGENT_ID_NUMBER <=", value, "agentIdNumber");
			return (Criteria) this;
		}

		public Criteria andAgentIdNumberLike(String value) {
			addCriterion("AGENT_ID_NUMBER like", value, "agentIdNumber");
			return (Criteria) this;
		}

		public Criteria andAgentIdNumberNotLike(String value) {
			addCriterion("AGENT_ID_NUMBER not like", value, "agentIdNumber");
			return (Criteria) this;
		}

		public Criteria andAgentIdNumberIn(List<String> values) {
			addCriterion("AGENT_ID_NUMBER in", values, "agentIdNumber");
			return (Criteria) this;
		}

		public Criteria andAgentIdNumberNotIn(List<String> values) {
			addCriterion("AGENT_ID_NUMBER not in", values, "agentIdNumber");
			return (Criteria) this;
		}

		public Criteria andAgentIdNumberBetween(String value1, String value2) {
			addCriterion("AGENT_ID_NUMBER between", value1, value2, "agentIdNumber");
			return (Criteria) this;
		}

		public Criteria andAgentIdNumberNotBetween(String value1, String value2) {
			addCriterion("AGENT_ID_NUMBER not between", value1, value2, "agentIdNumber");
			return (Criteria) this;
		}

		public Criteria andAgentFullNameIsNull() {
			addCriterion("AGENT_FULL_NAME is null");
			return (Criteria) this;
		}

		public Criteria andAgentFullNameIsNotNull() {
			addCriterion("AGENT_FULL_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andAgentFullNameEqualTo(String value) {
			addCriterion("AGENT_FULL_NAME =", value, "agentFullName");
			return (Criteria) this;
		}

		public Criteria andAgentFullNameNotEqualTo(String value) {
			addCriterion("AGENT_FULL_NAME <>", value, "agentFullName");
			return (Criteria) this;
		}

		public Criteria andAgentFullNameGreaterThan(String value) {
			addCriterion("AGENT_FULL_NAME >", value, "agentFullName");
			return (Criteria) this;
		}

		public Criteria andAgentFullNameGreaterThanOrEqualTo(String value) {
			addCriterion("AGENT_FULL_NAME >=", value, "agentFullName");
			return (Criteria) this;
		}

		public Criteria andAgentFullNameLessThan(String value) {
			addCriterion("AGENT_FULL_NAME <", value, "agentFullName");
			return (Criteria) this;
		}

		public Criteria andAgentFullNameLessThanOrEqualTo(String value) {
			addCriterion("AGENT_FULL_NAME <=", value, "agentFullName");
			return (Criteria) this;
		}

		public Criteria andAgentFullNameLike(String value) {
			addCriterion("AGENT_FULL_NAME like", value, "agentFullName");
			return (Criteria) this;
		}

		public Criteria andAgentFullNameNotLike(String value) {
			addCriterion("AGENT_FULL_NAME not like", value, "agentFullName");
			return (Criteria) this;
		}

		public Criteria andAgentFullNameIn(List<String> values) {
			addCriterion("AGENT_FULL_NAME in", values, "agentFullName");
			return (Criteria) this;
		}

		public Criteria andAgentFullNameNotIn(List<String> values) {
			addCriterion("AGENT_FULL_NAME not in", values, "agentFullName");
			return (Criteria) this;
		}

		public Criteria andAgentFullNameBetween(String value1, String value2) {
			addCriterion("AGENT_FULL_NAME between", value1, value2, "agentFullName");
			return (Criteria) this;
		}

		public Criteria andAgentFullNameNotBetween(String value1, String value2) {
			addCriterion("AGENT_FULL_NAME not between", value1, value2, "agentFullName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ORG_AGENT_INFO
     *
     * @mbg.generated do_not_delete_during_merge Tue Feb 26 16:03:49 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}