package com.thfdcsoft.framework.manage.entity;

public class OrgAgentInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ORG_AGENT_INFO.AGENT_ID
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	private String agentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ORG_AGENT_INFO.ORG_ID
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	private String orgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ORG_AGENT_INFO.AGENT_ID_NUMBER
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	private String agentIdNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ORG_AGENT_INFO.AGENT_FULL_NAME
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	private String agentFullName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ORG_AGENT_INFO.AGENT_ID
	 * @return  the value of ORG_AGENT_INFO.AGENT_ID
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public String getAgentId() {
		return agentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ORG_AGENT_INFO.AGENT_ID
	 * @param agentId  the value for ORG_AGENT_INFO.AGENT_ID
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public void setAgentId(String agentId) {
		this.agentId = agentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ORG_AGENT_INFO.ORG_ID
	 * @return  the value of ORG_AGENT_INFO.ORG_ID
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public String getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ORG_AGENT_INFO.ORG_ID
	 * @param orgId  the value for ORG_AGENT_INFO.ORG_ID
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ORG_AGENT_INFO.AGENT_ID_NUMBER
	 * @return  the value of ORG_AGENT_INFO.AGENT_ID_NUMBER
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public String getAgentIdNumber() {
		return agentIdNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ORG_AGENT_INFO.AGENT_ID_NUMBER
	 * @param agentIdNumber  the value for ORG_AGENT_INFO.AGENT_ID_NUMBER
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public void setAgentIdNumber(String agentIdNumber) {
		this.agentIdNumber = agentIdNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ORG_AGENT_INFO.AGENT_FULL_NAME
	 * @return  the value of ORG_AGENT_INFO.AGENT_FULL_NAME
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public String getAgentFullName() {
		return agentFullName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ORG_AGENT_INFO.AGENT_FULL_NAME
	 * @param agentFullName  the value for ORG_AGENT_INFO.AGENT_FULL_NAME
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public void setAgentFullName(String agentFullName) {
		this.agentFullName = agentFullName;
	}
}