package com.thfdcsoft.framework.manage.entity;

public class OrgInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ORG_INFO.ORG_ID
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	private String orgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ORG_INFO.ORG_NAME
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	private String orgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ORG_INFO.ORG_CODE
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	private String orgCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ORG_INFO.ORG_ID
	 * @return  the value of ORG_INFO.ORG_ID
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public String getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ORG_INFO.ORG_ID
	 * @param orgId  the value for ORG_INFO.ORG_ID
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ORG_INFO.ORG_NAME
	 * @return  the value of ORG_INFO.ORG_NAME
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public String getOrgName() {
		return orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ORG_INFO.ORG_NAME
	 * @param orgName  the value for ORG_INFO.ORG_NAME
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ORG_INFO.ORG_CODE
	 * @return  the value of ORG_INFO.ORG_CODE
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public String getOrgCode() {
		return orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ORG_INFO.ORG_CODE
	 * @param orgCode  the value for ORG_INFO.ORG_CODE
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}
}