package com.thfdcsoft.framework.manage.entity;

public class RoleInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ROLE_INFO.ROLE_ID
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	private String roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ROLE_INFO.ROLE_NAME
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ROLE_INFO.ROLE_DESCRIBE
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	private String roleDescribe;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ROLE_INFO.ROLE_ID
	 * @return  the value of ROLE_INFO.ROLE_ID
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ROLE_INFO.ROLE_ID
	 * @param roleId  the value for ROLE_INFO.ROLE_ID
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ROLE_INFO.ROLE_NAME
	 * @return  the value of ROLE_INFO.ROLE_NAME
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ROLE_INFO.ROLE_NAME
	 * @param roleName  the value for ROLE_INFO.ROLE_NAME
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ROLE_INFO.ROLE_DESCRIBE
	 * @return  the value of ROLE_INFO.ROLE_DESCRIBE
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public String getRoleDescribe() {
		return roleDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ROLE_INFO.ROLE_DESCRIBE
	 * @param roleDescribe  the value for ROLE_INFO.ROLE_DESCRIBE
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	public void setRoleDescribe(String roleDescribe) {
		this.roleDescribe = roleDescribe;
	}
}