package com.thfdcsoft.framework.manage.entity;

public class UsageRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usage_record.RECORD_ID
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	private String recordId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usage_record.USER_IDNUMBER
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	private String userIdnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usage_record.USER_FULLNAME
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	private String userFullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usage_record.DEVICE_NUMBER
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	private String deviceNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usage_record.USAGE_TIME
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	private String usageTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usage_record.USER_ID_PIC_PATH
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	private String userIdPicPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usage_record.USER_DET_PIC_PATH
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	private String userDetPicPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usage_record.USER_LOG_PATH
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	private String userLogPath;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usage_record.RECORD_ID
	 * @return  the value of usage_record.RECORD_ID
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	public String getRecordId() {
		return recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usage_record.RECORD_ID
	 * @param recordId  the value for usage_record.RECORD_ID
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	public void setRecordId(String recordId) {
		this.recordId = recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usage_record.USER_IDNUMBER
	 * @return  the value of usage_record.USER_IDNUMBER
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	public String getUserIdnumber() {
		return userIdnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usage_record.USER_IDNUMBER
	 * @param userIdnumber  the value for usage_record.USER_IDNUMBER
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	public void setUserIdnumber(String userIdnumber) {
		this.userIdnumber = userIdnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usage_record.USER_FULLNAME
	 * @return  the value of usage_record.USER_FULLNAME
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	public String getUserFullname() {
		return userFullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usage_record.USER_FULLNAME
	 * @param userFullname  the value for usage_record.USER_FULLNAME
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	public void setUserFullname(String userFullname) {
		this.userFullname = userFullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usage_record.DEVICE_NUMBER
	 * @return  the value of usage_record.DEVICE_NUMBER
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	public String getDeviceNumber() {
		return deviceNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usage_record.DEVICE_NUMBER
	 * @param deviceNumber  the value for usage_record.DEVICE_NUMBER
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	public void setDeviceNumber(String deviceNumber) {
		this.deviceNumber = deviceNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usage_record.USAGE_TIME
	 * @return  the value of usage_record.USAGE_TIME
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	public String getUsageTime() {
		return usageTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usage_record.USAGE_TIME
	 * @param usageTime  the value for usage_record.USAGE_TIME
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	public void setUsageTime(String usageTime) {
		this.usageTime = usageTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usage_record.USER_ID_PIC_PATH
	 * @return  the value of usage_record.USER_ID_PIC_PATH
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	public String getUserIdPicPath() {
		return userIdPicPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usage_record.USER_ID_PIC_PATH
	 * @param userIdPicPath  the value for usage_record.USER_ID_PIC_PATH
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	public void setUserIdPicPath(String userIdPicPath) {
		this.userIdPicPath = userIdPicPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usage_record.USER_DET_PIC_PATH
	 * @return  the value of usage_record.USER_DET_PIC_PATH
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	public String getUserDetPicPath() {
		return userDetPicPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usage_record.USER_DET_PIC_PATH
	 * @param userDetPicPath  the value for usage_record.USER_DET_PIC_PATH
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	public void setUserDetPicPath(String userDetPicPath) {
		this.userDetPicPath = userDetPicPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usage_record.USER_LOG_PATH
	 * @return  the value of usage_record.USER_LOG_PATH
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	public String getUserLogPath() {
		return userLogPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usage_record.USER_LOG_PATH
	 * @param userLogPath  the value for usage_record.USER_LOG_PATH
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	public void setUserLogPath(String userLogPath) {
		this.userLogPath = userLogPath;
	}
}