package com.thfdcsoft.framework.manage.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.thfdcsoft.framework.manage.entity.AuthorizeInfoExample;
import com.thfdcsoft.framework.manage.entity.AuthorizeInfoKey;

public interface AuthorizeInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AUTHORIZE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	long countByExample(AuthorizeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AUTHORIZE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int deleteByExample(AuthorizeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AUTHORIZE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int deleteByPrimaryKey(AuthorizeInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AUTHORIZE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int insert(AuthorizeInfoKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AUTHORIZE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int insertSelective(AuthorizeInfoKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AUTHORIZE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	List<AuthorizeInfoKey> selectByExample(AuthorizeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AUTHORIZE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int updateByExampleSelective(@Param("record") AuthorizeInfoKey record,
			@Param("example") AuthorizeInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AUTHORIZE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int updateByExample(@Param("record") AuthorizeInfoKey record, @Param("example") AuthorizeInfoExample example);
}