package com.thfdcsoft.framework.manage.dao;

import com.thfdcsoft.framework.manage.entity.BusiInfo;
import com.thfdcsoft.framework.manage.entity.BusiInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusiInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    long countByExample(BusiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    int deleteByExample(BusiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    int deleteByPrimaryKey(String busiNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    int insert(BusiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    int insertSelective(BusiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    List<BusiInfo> selectByExample(BusiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    BusiInfo selectByPrimaryKey(String busiNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") BusiInfo record, @Param("example") BusiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    int updateByExample(@Param("record") BusiInfo record, @Param("example") BusiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    int updateByPrimaryKeySelective(BusiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUSI_INFO
     *
     * @mbg.generated Thu Jul 12 13:49:07 CST 2018
     */
    int updateByPrimaryKey(BusiInfo record);
}