package com.thfdcsoft.framework.manage.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.thfdcsoft.framework.manage.entity.Help;
import com.thfdcsoft.framework.manage.entity.HelpExample;
import com.thfdcsoft.framework.manage.entity.OrgAgentInfoExample;

public interface HelpMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	long countByExample(HelpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	int deleteByExample(HelpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	int deleteByPrimaryKey(String recordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	int insert(Help record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	int insertSelective(Help record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	List<Help> selectByExample(HelpExample example);
	
	PageList<Help> selectByExample(HelpExample example, PageBounds pageBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	Help selectByPrimaryKey(String recordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Help record, @Param("example") HelpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	int updateByExample(@Param("record") Help record, @Param("example") HelpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	int updateByPrimaryKeySelective(Help record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table help
	 * @mbg.generated  Fri Jul 05 16:27:52 CST 2019
	 */
	int updateByPrimaryKey(Help record);

}