package com.thfdcsoft.framework.manage.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.thfdcsoft.framework.manage.entity.ModuleInfo;
import com.thfdcsoft.framework.manage.entity.ModuleInfoExample;

public interface ModuleInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	long countByExample(ModuleInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int deleteByExample(ModuleInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int deleteByPrimaryKey(String moduleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int insert(ModuleInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int insertSelective(ModuleInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	List<ModuleInfo> selectByExample(ModuleInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	ModuleInfo selectByPrimaryKey(String moduleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ModuleInfo record, @Param("example") ModuleInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int updateByExample(@Param("record") ModuleInfo record, @Param("example") ModuleInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int updateByPrimaryKeySelective(ModuleInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int updateByPrimaryKey(ModuleInfo record);
}