package com.thfdcsoft.framework.manage.dao;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.thfdcsoft.framework.manage.entity.OrgAgentInfo;
import com.thfdcsoft.framework.manage.entity.OrgAgentInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrgAgentInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	long countByExample(OrgAgentInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	int deleteByExample(OrgAgentInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	int deleteByPrimaryKey(String agentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	int insert(OrgAgentInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	int insertSelective(OrgAgentInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	List<OrgAgentInfo> selectByExample(OrgAgentInfoExample example);
	
	PageList<OrgAgentInfo> selectByExample(OrgAgentInfoExample example, PageBounds pageBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	OrgAgentInfo selectByPrimaryKey(String agentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	int updateByExampleSelective(@Param("record") OrgAgentInfo record, @Param("example") OrgAgentInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	int updateByExample(@Param("record") OrgAgentInfo record, @Param("example") OrgAgentInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	int updateByPrimaryKeySelective(OrgAgentInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_AGENT_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	int updateByPrimaryKey(OrgAgentInfo record);
}