package com.thfdcsoft.framework.manage.dao;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.thfdcsoft.framework.manage.entity.OrgInfo;
import com.thfdcsoft.framework.manage.entity.OrgInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrgInfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	long countByExample(OrgInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	int deleteByExample(OrgInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	int deleteByPrimaryKey(String orgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	int insert(OrgInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	int insertSelective(OrgInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	List<OrgInfo> selectByExample(OrgInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	OrgInfo selectByPrimaryKey(String orgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	int updateByExampleSelective(@Param("record") OrgInfo record, @Param("example") OrgInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	int updateByExample(@Param("record") OrgInfo record, @Param("example") OrgInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	int updateByPrimaryKeySelective(OrgInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ORG_INFO
	 * @mbg.generated  Wed Feb 27 19:23:05 CST 2019
	 */
	int updateByPrimaryKey(OrgInfo record);

	PageList<OrgInfo> selectByExample(OrgInfoExample example, PageBounds pageBounds);
}