package com.thfdcsoft.framework.manage.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.thfdcsoft.framework.manage.entity.RoleInfo;
import com.thfdcsoft.framework.manage.entity.RoleInfoExample;

public interface RoleInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ROLE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	long countByExample(RoleInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ROLE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int deleteByExample(RoleInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ROLE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int deleteByPrimaryKey(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ROLE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int insert(RoleInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ROLE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int insertSelective(RoleInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ROLE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	List<RoleInfo> selectByExample(RoleInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ROLE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	RoleInfo selectByPrimaryKey(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ROLE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int updateByExampleSelective(@Param("record") RoleInfo record, @Param("example") RoleInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ROLE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int updateByExample(@Param("record") RoleInfo record, @Param("example") RoleInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ROLE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int updateByPrimaryKeySelective(RoleInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ROLE_INFO
	 * @mbg.generated  Wed Nov 22 11:37:43 CST 2017
	 */
	int updateByPrimaryKey(RoleInfo record);
}