package com.thfdcsoft.framework.manage.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.thfdcsoft.framework.manage.entity.TerminalInfo;
import com.thfdcsoft.framework.manage.entity.TerminalInfoExample;

public interface TerminalInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Wed Jun 27 19:40:07 CST 2018
	 */
	long countByExample(TerminalInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Wed Jun 27 19:40:07 CST 2018
	 */
	int deleteByExample(TerminalInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Wed Jun 27 19:40:07 CST 2018
	 */
	int deleteByPrimaryKey(String terminalId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Wed Jun 27 19:40:07 CST 2018
	 */
	int insert(TerminalInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Wed Jun 27 19:40:07 CST 2018
	 */
	int insertSelective(TerminalInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Wed Jun 27 19:40:07 CST 2018
	 */
	List<TerminalInfo> selectByExample(TerminalInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Wed Jun 27 19:40:07 CST 2018
	 */
	TerminalInfo selectByPrimaryKey(String terminalId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Wed Jun 27 19:40:07 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TerminalInfo record, @Param("example") TerminalInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Wed Jun 27 19:40:07 CST 2018
	 */
	int updateByExample(@Param("record") TerminalInfo record, @Param("example") TerminalInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Wed Jun 27 19:40:07 CST 2018
	 */
	int updateByPrimaryKeySelective(TerminalInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TERMINAL_INFO
	 * @mbg.generated  Wed Jun 27 19:40:07 CST 2018
	 */
	int updateByPrimaryKey(TerminalInfo record);
	
	TerminalInfo selectByDeployNumber(String deployNumber);
	
	//修改每次的随机数
	int updateBydeploy_number(TerminalInfo record);

	// 通过设备编号和打印模块编号获取设备信息
    TerminalInfo selectByDeployNumberAndTernimalId(@Param("deviceNumber")String deviceNumber, @Param("terminalId")String terminalId);
}