package com.thfdcsoft.framework.manage.dao;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.thfdcsoft.framework.manage.entity.UsageRecord;
import com.thfdcsoft.framework.manage.entity.UsageRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsageRecordMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usage_record
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	long countByExample(UsageRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usage_record
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	int deleteByExample(UsageRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usage_record
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	int deleteByPrimaryKey(String recordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usage_record
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	int insert(UsageRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usage_record
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	int insertSelective(UsageRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usage_record
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	List<UsageRecord> selectByExample(UsageRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usage_record
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	UsageRecord selectByPrimaryKey(String recordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usage_record
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	int updateByExampleSelective(@Param("record") UsageRecord record, @Param("example") UsageRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usage_record
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	int updateByExample(@Param("record") UsageRecord record, @Param("example") UsageRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usage_record
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	int updateByPrimaryKeySelective(UsageRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usage_record
	 * @mbg.generated  Thu May 09 11:46:12 CST 2019
	 */
	int updateByPrimaryKey(UsageRecord record);

	PageList<UsageRecord> selectByExample(UsageRecordExample example, PageBounds pageBounds);

	UsageRecord selectByRecordId(String recordId);

}